### ISSUE TITLE
"Do NOT recreate old video page layout" not working

### ISSUE THREAD

**Issue by datnguyen8128** [the-omnipotent/YouTubeRedux#1]
I don't know if it's just me or that tick button isn't working. I reloaded, reopened the tab and restarted the browser but it still stays on the old layout

**Comment by the-omnipotent** [comment]
Keep in mind this setting disables rearranged elements like the subscribe button, channel info, likes/dislikes bar, upload date, views, share and save buttons etc. It doesn't affect things like related videos or comments.

It works fine for me so if it still doesn't change anything then please attach a pair of before/after screenshots as well as tell me what browser version you're using.
